Closes #331 -- ensure latest clean master before creating a new release

diff --git a/deployment/release b/deployment/release
--- a/deployment/release
+++ b/deployment/release
@@ -45,12 +45,18 @@ run() {
 }
 
 new() {
-	BRANCH=$(${SEMVER} -i minor ${VERSION})
-	run "Creating release branch ${BRANCH}" git checkout -b ${BRANCH}
-	run "Tagging release" npmversion minor
-	run "Incrementing master version" git checkout master
-	run "" npmversion $(${SEMVER} --preid ${PREID} -i preminor ${VERSION})
-	run "Pushing to origin" git push origin --tags master ${BRANCH}
+	# Only run if current working directory is clean and on branch 'master'
+	if [ git diff-index --quiet HEAD -- ] && [ "$BRANCH_NAME" -eq "master" ]; then
+		run git pull origin master
+		BRANCH=$(${SEMVER} -i minor ${VERSION})
+		run "Creating release branch ${BRANCH}" git checkout -b ${BRANCH}
+		run "Tagging release" npmversion minor
+		run "Incrementing master version" git checkout master
+		run "" npmversion $(${SEMVER} --preid ${PREID} -i preminor ${VERSION})
+		run "Pushing to origin" git push origin --tags master ${BRANCH}
+	else
+		{ echo "Error $? running '${cmd}' because git working directory is not clean and/or not on branch 'master'."; FAILED=true; }
+	fi
 #	run "Publishing" git checkout ${BRANCH}
 #	run "" npm publish
 }
@@ -99,18 +105,11 @@ fi
 
 cmd="$1"
 
-# Only run if current working directory is clean and on branch 'master'
-if [ git diff-index --quiet HEAD -- ] && [ "$BRANCH_NAME" -eq "master" ]; then
-	echo "No DIFF STUFF"
-	case "$cmd" in
-	    new) new;;
-	    patch) patch "$@";;
-	    major) major;;
-		testing) testing;;
-	    "") usage;;
-	    *) usage;;
-	esac
-else
-	{ echo "Error $? running '${cmd}' because git working directory is not clean and/or not on branch 'master'."; FAILED=true; }
-fi
-
+case "$cmd" in
+    new) new;;
+    patch) patch "$@";;
+    major) major;;
+	testing) testing;;
+    "") usage;;
+    *) usage;;
+esac
