prevent release if not on clean master branch

diff --git a/deployment/release b/deployment/release
--- a/deployment/release
+++ b/deployment/release
@@ -8,6 +8,11 @@ PREID=alpha
 DIR=$(dirname "${BASH_SOURCE[0]}")
 cd ${DIR}/../website
 
+# Get name of current branch
+BRANCH_NAME="$(git symbolic-ref HEAD 2>/dev/null)" ||
+BRANCH_NAME="(unnamed branch)"     # detached HEAD
+BRANCH_NAME=${BRANCH_NAME##refs/heads/}
+
 # Horrible work-around for 'npm version'
 # https://github.com/npm/npm/issues/9111
 npmversion() {
@@ -36,14 +41,6 @@ run() {
 		echo "'${cmd}' skipped due to earlier error."
     else
 		eval "$cmd" || { echo "Error $? running '${cmd}'"; FAILED=true; }
-	fi
-}
-
-testing() {
-	if git diff-index --quiet HEAD --; then
-    	echo "DIFF STUFF"
-	else
-    	echo "NO DIFF STUFF"
 	fi
 }
 
@@ -102,11 +99,18 @@ fi
 
 cmd="$1"
 
-case "$cmd" in
-    new) new;;
-    patch) patch "$@";;
-    major) major;;
-	testing) testing;;
-    "") usage;;
-    *) usage;;
-esac
+# Only run if current working directory is clean and on branch 'master'
+if [ git diff-index --quiet HEAD -- ] && [ "$BRANCH_NAME" -eq "master" ]; then
+	echo "No DIFF STUFF"
+	case "$cmd" in
+	    new) new;;
+	    patch) patch "$@";;
+	    major) major;;
+		testing) testing;;
+	    "") usage;;
+	    *) usage;;
+	esac
+else
+	{ echo "Error $? running '${cmd}' because git working directory is not clean and/or not on branch 'master'."; FAILED=true; }
+fi
+
